name: 'grcov for Rust'
description: 'Collect and aggregate code coverage information with the Mozilla grcov tool'
author: 'Alessandro Chitolina'
branding:
  icon: play-circle
  color: gray-dark
inputs:
  config:
    description: Path to the configuration file (optional, relative to the repository root)
    required: false
    default: .github/actions-rs/grcov.yml

outputs:
  report:
    description: Absolute path to the generated code coverage file

runs:
  using: 'node16'
  main: 'dist/index.js'
